export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

export const FETCH_RESTAURANT_DATA = "FETCH_RESTAURANT_DATA";
export const FETCH_RESTAURANT_DATA_SUCCESS = "FETCH_RESTAURANT_DATA_SUCCESS";
export const FETCH_RESTAURANT_DATA_FAILED = "FETCH_RESTAURANT_DATA_FAILED";

export const FILTER_ALL = "FILTER_ALL";
export const FILTER_RATING = "FILTER_RATING";
export const FILTER_VEG = "FILTER_VEG";

export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";